### ISSUE TITLE
Decimal gold should not be shown to the user

### ISSUE THREAD

**Issue by tildejustin** [Squirrel-314/Gold-Rush#15]

**Comment by tildejustin** [comment]
when less than one

**Comment by hnasheralneam** [comment]
Ok, I'll only use decimals if gold is less than one

**Comment by tildejustin** [comment]
No I mean the opposite of that. The user should not have to worry about fractional gold, it should just show a number rounded down

**Comment by hnasheralneam** [comment]
Will implement in next version

**Comment by hnasheralneam** [comment]
Ok will do

**Comment by hnasheralneam** [comment]
Completed with v2.0.0
